# Generated by Django 4.1.3 on 2022-11-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password1_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Добавить пользователя', 'verbose_name_plural': 'Добавить пользователя'},
        ),
    ]
