# Generated by Django 4.1.1 on 2022-12-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Добавить пользователя'},
        ),
    ]
