# Generated by Django 4.1.3 on 2022-11-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('SecondName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Departament', models.CharField(max_length=100)),
                ('Login', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
