# Generated by Django 4.1.3 on 2022-11-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['FirstName', 'SecondName', 'LastName'], 'verbose_name': 'Сотрудники компании', 'verbose_name_plural': 'Сотрудники компании'},
        ),
        migrations.AlterField(
            model_name='person',
            name='Departament',
            field=models.CharField(max_length=100, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='person',
            name='FirstName',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='LastName',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='SecondName',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
