# Generated by Django 4.1.3 on 2022-11-18 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0003_question_alter_person_options_alter_person_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 21, 31, 40, 419117), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
            preserve_default=False,
        ),
    ]
