# Generated by Django 4.1.3 on 2022-11-19 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0005_alter_answer_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 20, 58, 54, 432583), verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
