# Generated by Django 4.1.3 on 2022-11-19 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0008_alter_question_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 37, 51, 476215), verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
