# Generated by Django 4.1.1 on 2022-11-23 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0015_alter_question_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 10, 58, 23, 521263), verbose_name='Дата публикации'),
        ),
    ]
