# Generated by Django 4.1.1 on 2022-12-06 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0017_alter_question_date_published_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['FirstName', 'SecondName', 'LastName'], 'verbose_name': 'Статистика сотрудника компании', 'verbose_name_plural': 'Статистика сотрудники компании'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='Login',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='success',
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 14, 18, 58, 426102), verbose_name='Дата публикации'),
        ),
    ]
