# Generated by Django 4.1.1 on 2022-12-06 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0018_alter_person_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['FirstName', 'SecondName', 'LastName'], 'verbose_name_plural': 'Статистика сотрудники компании'},
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 14, 22, 38, 93304), verbose_name='Дата публикации'),
        ),
    ]
