# Generated by Django 4.1.1 on 2022-12-06 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0022_alter_person_date_finish_alter_person_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discriptionquestion',
            options={'verbose_name': 'Комментарии к правильному ответу на вопрос теста', 'verbose_name_plural': 'Комментарии к правильному ответу на вопрос теста'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Добавить новый вопрос', 'verbose_name_plural': 'Добавить новый вопрос'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Добавить новый тест', 'verbose_name_plural': 'Добавить новый тест'},
        ),
        migrations.AlterField(
            model_name='person',
            name='Date_finish',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 15, 25, 5, 886038), verbose_name='Дата завершения теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 15, 25, 5, 887036), verbose_name='Дата публикации'),
        ),
    ]
