# Generated by Django 4.1.1 on 2022-12-06 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0024_alter_discriptionquestion_name_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Image',
        ),
        migrations.AlterField(
            model_name='person',
            name='Date_finish',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 16, 58, 17, 685770), verbose_name='Дата завершения теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 16, 58, 17, 685770), verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='PersonAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parma.person')),
            ],
        ),
    ]
