# Generated by Django 4.1.1 on 2022-12-06 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0028_alter_person_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Date_finish',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 17, 24, 27, 255787), verbose_name='Дата завершения теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 17, 24, 27, 256794), verbose_name='Дата публикации'),
        ),
    ]
