# Generated by Django 4.1.1 on 2022-12-06 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0031_alter_person_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Date_finish',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 18, 21, 45, 766125), verbose_name='Дата завершения теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 18, 21, 45, 767041), verbose_name='Дата публикации'),
        ),
    ]
