# Generated by Django 4.1.1 on 2022-12-06 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0032_alter_person_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['FirstName', 'SecondName'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='LastName',
        ),
        migrations.AlterField(
            model_name='discriptionquestion',
            name='Name_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parma.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Date_finish',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 18, 47, 54, 588456), verbose_name='Дата завершения теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 18, 47, 54, 589454), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='q1',
            field=models.ManyToManyField(to='parma.question', verbose_name='Вопросы'),
        ),
    ]
