# Generated by Django 4.1.1 on 2022-12-07 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0033_alter_person_options_remove_person_lastname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discriptionquestion',
            options={'verbose_name': 'комментарии к правильному ответу на вопрос теста', 'verbose_name_plural': 'комментарии к правильному ответу на вопрос теста'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'новый вопрос', 'verbose_name_plural': 'новый вопрос'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'новый тест', 'verbose_name_plural': 'новый тест'},
        ),
        migrations.AlterField(
            model_name='person',
            name='Date_finish',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 27, 45, 797994), verbose_name='Дата завершения теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 27, 45, 797994), verbose_name='Дата публикации'),
        ),
    ]
