# Generated by Django 4.1.1 on 2022-12-08 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0036_discriptionquestion_image_alter_person_date_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discriptionquestion',
            name='video',
            field=models.FileField(default=0, upload_to='static/', verbose_name='Загрузите видео - пояснение к вопросу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(default=0, upload_to='static/', verbose_name='Загрузите вспомогательное видео для вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='Date_finish',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 0, 22, 4, 792450), verbose_name='Дата завершения теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 0, 22, 4, 793450), verbose_name='Дата публикации'),
        ),
    ]
